### ISSUE TITLE
division by zero error in compute_rows_per_partition

### ISSUE THREAD

**Issue by awesomo4000** [hakonmh/featherstore#5]
Division by zero error when attempting `store.write_table` with a dataframe of length zero.

code:

```
import polars as pl
import featherstore as fs
fs.create_database("./test-fs")
fs.connect("./test-fs")
fs.create_store("test_store")
store = fs.Store("test_store")
empty_df = pl.DataFrame(schema={"A":str})
store.write_table('test_table', empty_df)
```
traceback:
```
Traceback (most recent call last):
  File "fs_div0.py", line 10, in <module>
    store.write_table('test_table', empty_df)
  File ".venv/lib/python3.11/site-packages/featherstore/store.py", line 281, in write_table
    Table(table_name, self.name).write(
  File ".venv/lib/python3.11/site-packages/featherstore/table.py", line 163, in write
    rows_per_partition = common.compute_rows_per_partition(df, partition_size)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/featherstore/_table/common.py", line 171, in compute_rows_per_partition
    rows_per_partition = num_rows * target_size / table_size_in_bytes
                         ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

```

**Comment by hakonmh** [comment]
It should work as expected now

**Comment by awesomo4000** [comment]
Thank you !
